### ISSUE TITLE
Racon has changed 

### ISSUE THREAD

**Issue by mictadlo** [HadrienG/nanoflow#12]
Hi, 
Racon has changed. Do you have any plans to update Racon in your workflow?

Thank you in advance.

Best wishes,

Michal

**Comment by HadrienG** [comment]
Hi!

Thanks for brining that to my attention. 
Yes ideally I'd like to switch to versioned docker but haven;t had time to do that yet.

I the meantime I'll update the racon:latest container and process (if needed) asap.

Best,
Hadrien

**Comment by mictadlo** [comment]
Here is an example how to run it (https://github.com/isovic/racon/issues/69#issuecomment-381781156)

**Comment by HadrienG** [comment]
Hi!

racon should now work again. Note that `nanoflow` at the moment only performs 1 round of polishing when used with `miniasm`. If you need several rounds (and are working with bacteria) I recommend running with `unicycler`, which will perform several `racon` iterations and only stop when the assembly does not improve anymore.

Best,
Hadrien
