### ISSUE TITLE
Problem with planet execution

### ISSUE THREAD

**Issue by Ackia** [HadrienG/nanoflow#8]
Dependencies:
    Program         Version   Status  
    spades.py                 not used
    racon           -         bad     
    makeblastdb     2.6.0+    good    
    tblastn         2.6.0+    good    
    bowtie2-build             not used
    bowtie2                   not used
    samtools                  not used
    java                      not used
    pilon                     not used
    bcftools                  not used

Command error:
  tput: No value for $TERM and no -T specified
  tput: No value for $TERM and no -T specified
  tput: No value for $TERM and no -T specified
  Error: Racon was found but does not produce output

**Comment by HadrienG** [comment]
I did fix racon!
If only I also made Unicycler load the correct racon version...
