### ISSUE TITLE
Error using profile planet

### ISSUE THREAD

**Issue by Ackia** [HadrienG/nanoflow#9]
[oskar@planetsmasher Assembly_Unicycler]$ nextflow run hadrieng/nanoflow --reads ~/Anna_Plasmid/1_Basecalls_20180223/workspace/pass --assembler unicycler --output results --profile planet
N E X T F L O W  ~  version 0.26.2
Launching `hadrieng/nanoflow` [friendly_allen] - revision: 8bc209d00c [master]
[warm up] executor > local
[00/c2365d] Submitted process > adapter_trimming
ERROR ~ Error executing process > 'adapter_trimming'

Caused by:
  Process `adapter_trimming` terminated with an error exit status (127)

Command executed:

  porechop -i "pass" -t "4" -o trimmed.fastq

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 69: docker: command not found

Work dir:
  /export/home/oskar/Anna_Plasmid/Analysis/Assembly_Unicycler/work/00/c2365dce22286f16b0b84fcf6560a9

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details

**Comment by Ackia** [comment]
Mar-20 15:19:08.343 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/oskar/.nextflow/assets/hadrieng/nanoflow/bin
Mar-20 15:19:08.448 [main] DEBUG nextflow.Session - Session start invoked
Mar-20 15:19:08.452 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Mar-20 15:19:08.452 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Mar-20 15:19:08.673 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-20 15:19:08.772 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Mar-20 15:19:08.772 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-20 15:19:08.780 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-20 15:19:08.783 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Mar-20 15:19:08.788 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=24; memory=125.7 GB; capacity=24; pollInterval=100ms; dumpInterval=5m
Mar-20 15:19:08.793 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Mar-20 15:19:08.794 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Mar-20 15:19:08.797 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Mar-20 15:19:08.865 [main] DEBUG nextflow.Session - >>> barrier register (process: adapter_trimming)
Mar-20 15:19:08.868 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > adapter_trimming -- maxForks: 24
Mar-20 15:19:08.966 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Mar-20 15:19:08.966 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-20 15:19:08.966 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-20 15:19:08.967 [main] DEBUG nextflow.Session - >>> barrier register (process: assembly)
Mar-20 15:19:08.968 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > assembly -- maxForks: 24
Mar-20 15:19:08.973 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Mar-20 15:19:08.973 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-20 15:19:08.974 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-20 15:19:08.975 [main] DEBUG nextflow.Session - >>> barrier register (process: consensus)
Mar-20 15:19:08.976 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > consensus -- maxForks: 24
Mar-20 15:19:08.983 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: local
Mar-20 15:19:08.983 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Mar-20 15:19:08.984 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Mar-20 15:19:08.985 [main] DEBUG nextflow.Session - >>> barrier register (process: polishing)
Mar-20 15:19:08.985 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > polishing -- maxForks: 24
Mar-20 15:19:08.987 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Mar-20 15:19:08.987 [main] DEBUG nextflow.Session - Session await
Mar-20 15:19:09.115 [Task submitter] INFO  nextflow.Session - [00/c2365d] Submitted process > adapter_trimming
Mar-20 15:19:09.193 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: adapter_trimming; status: COMPLETED; exit: 127; error: -; workDir: /export/home/oskar/Anna_Plasmid/Analysis/Assembly_Unicycler/work/00/c2365dce22286f16b0b84fcf6560a9]
Mar-20 15:19:09.238 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'adapter_trimming'

Caused by:
  Process `adapter_trimming` terminated with an error exit status (127)

Command executed:
  porechop -i "pass" -t "4" -o trimmed.fastq

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 69: docker: command not found

Work dir:
  /export/home/oskar/Anna_Plasmid/Analysis/Assembly_Unicycler/work/00/c2365dce22286f16b0b84fcf6560a9

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
Mar-20 15:19:09.242 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `adapter_trimming` terminated with an error exit status (127)
Mar-20 15:19:09.245 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: adapter_trimming)
Mar-20 15:19:09.246 [Actor Thread 7] DEBUG nextflow.Session - <<< barrier arrive (process: consensus)
Mar-20 15:19:09.246 [Actor Thread 6] DEBUG nextflow.Session - <<< barrier arrive (process: assembly)
Mar-20 15:19:09.246 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: polishing)
Mar-20 15:19:09.246 [main] DEBUG nextflow.Session - Session await > all process finished
Mar-20 15:19:09.268 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-20 15:19:09.268 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Mar-20 15:19:09.342 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Mar-20 15:19:09.352 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by HadrienG** [comment]
`nextflow` distinguished between pipeline specific parameters, starting with `--` and nextflow options, starting with `-`

`-profile` is a nextflow option, it should start with a single dash. In your current command it is passed to nexflow as a pipeline option and therefore `nanoflow` uses the default profile, which uses docker; our server does not have docker.

```
nextflow run hadrieng/nanoflow --reads ~/Anna_Plasmid/1_Basecalls_20180223/workspace/pass --assembler unicycler --output results -profile planet
```

should work
